# Generated by Django 4.1.4 on 2023-05-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="Saddress",
            field=models.TextField(max_length=300),
        ),
    ]
